### PR TITLE
Fix mass assign issues

### LINKED ISSUE #125: mass assign: give error when mass assigning one Worker multiple times in a single call
`assign s/2 w/2 cashier w/2 cleaner` doesnt give an error, and adds the first role (in this case cashier) and ignores the second.

### LINKED ISSUE #126: mass assign: prevent assigning over role limit in single call
assigning 3 workers with same role into a shift with only 2 role requirement is possible if done in a single call

### PR DESCRIPTION
**Pull request by sigmund-c**
resolves #125 and #126 .
Edited message for MESSAGE_INVALID_ASSIGNMENT_NOT_REQUIRED for clarity ("This role is not required for this position" -> "The %1$s role is not required or is filled for %2$s"

### CODE REVIEW

File: src/main/java/mcscheduler/logic/commands/AssignCommand.java [hunk 1]
```diff
@@ -91,12 +96,27 @@ public CommandResult execute(Model model) throws CommandException {
...
+                if (!requiredRoles.containsKey(role)) {
+                    requiredRoles.put(role, getQuantityRequiredForRole(shiftToAssign, role));
+                }
+                requiredRoles.put(role, requiredRoles.get(role) - 1);
+                if (requiredRoles.get(role) < 0) {
+                    // This assignCommand will exceed the role's requirement
+                    throw new CommandException(
+                        String.format(Messages.MESSAGE_INVALID_ASSIGNMENT_NOT_REQUIRED, role, shiftToAssign));
+                }
+            }
```
Comment (wakululuu) [inline src/main/java/mcscheduler/logic/commands/AssignCommand.java:116]: Not sure if this is necessary. Would it work if instead of this, we just put the original check

> if (!shiftToAssign.isRoleRequired(role)) {
>     throw new CommandException(Messages.MESSAGE_INVALID_ASSIGNMENT_NOT_REQUIRED);
> }

within the `for` loop before each `model.addAssignment(assignment)` call (ie. between lines 128 and 129)?

File: src/main/java/mcscheduler/logic/commands/AssignCommand.java [hunk 2]
```diff
@@ -91,12 +96,27 @@ public CommandResult execute(Model model) throws CommandException {
...
 
             Assignment assignmentToAdd = new Assignment(shiftToAssign, workerToAssign, role);
-            if (model.hasAssignment(assignmentToAdd)) {
+            // Prevent duplicates in model & Prevent duplicates in a single call
+            if (model.hasAssignment(assignmentToAdd) || assignmentsToAdd.contains(assignmentToAdd)) {
```
Comment (wakululuu) [inline src/main/java/mcscheduler/logic/commands/AssignCommand.java:120]: Same comment as above, I think we can just place this check in the `for` loop before adding each assignment as well.

**Review by wakululuu — CHANGES_REQUESTED** [review]
Not sure if some of your edits are necessary

File: src/main/java/mcscheduler/logic/commands/AssignCommand.java (hunk 1 above)
Comment (sigmund-c) [reply src/main/java/mcscheduler/logic/commands/AssignCommand.java:116]: Doing it that way will still add the previous assignments before the error assignment to the model. Then the feedback will be a command error rather than a command success, yet it still adds some new assignments. Though if there's a solution to this, do let me know!

Comment (wakululuu) [reply src/main/java/mcscheduler/logic/commands/AssignCommand.java:116]: Since `assignStringBuilder` keeps track of the assignments already added, perhaps we can concat the list of successful assignments to the `CommandException` thrown.

Comment (sigmund-c) [reply src/main/java/mcscheduler/logic/commands/AssignCommand.java:116]: I think if it returns an error, you shouldnt accept any part of the command to keep it consistent with other commands. Its also to makes sure the user knows that they're doing something wrong, and not accidentally add unwanted assignments.

Comment (wakululuu) [reply src/main/java/mcscheduler/logic/commands/AssignCommand.java:116]: That's a valid point

**Review by wakululuu — APPROVED** [review]
LGTM
