### PR TITLE
worker-pay bug fix and out of bounds index inconsistent error

### LINKED ISSUE #214: inconsistent invalid index message
when index not accepted by parser:
image
when index not accepted by model (index out of bounds)
image

### LINKED ISSUE #215: Change prefix for phone number to avoid confusion
change prefix

Change `p/PHONE_NUMBER` to `hp/PHONE_NUMBER`

### LINKED ISSUE #221: indicate how worker-pay is calculated?
Either in the return message or in the UG, should mention the complete formula. Maybe say something like
`Alex Yeoh's pay for the week: $10.00/hr * 3 shifts * 8 hours = $240.00`
or just mention in the UG

### LINKED ISSUE #228: worker-pay incorrectly treats leave as a valid role and includes that shift in calcuation
worker-pay currently includes leave taken on a shift as working on the shift and adds that shift into calculation

### PR DESCRIPTION
**Pull request by plosslaw**
Resolves #214 
Resolves #228 
Resolves #215 
Resolves #221

### CODE REVIEW

File: src/main/java/mcscheduler/logic/commands/CancelLeaveCommand.java [hunk 1]
```diff
@@ -105,6 +103,19 @@ public CommandResult execute(Model model) throws CommandException {
...
+        return String.format(Messages.MESSAGE_INVALID_COMMAND_FORMAT,
+                String.format(Messages.MESSAGE_INVALID_WORKER_DISPLAYED_INDEX, workerIndex.getOneBased())
+                        + MESSAGE_USAGE);
+    }
+
+    private String printOutOfBoundsShiftIndexError(Index shiftIndex) {
+        return String.format(Messages.MESSAGE_INVALID_COMMAND_FORMAT,
+                String.format(Messages.MESSAGE_INVALID_SHIFT_DISPLAYED_INDEX, shiftIndex.getOneBased())
+                        + MESSAGE_USAGE);
+    }
```
Comment (WangZijun97) [inline src/main/java/mcscheduler/logic/commands/CancelLeaveCommand.java:116]: Consider abstracting these methods to `CommandUtil` or some kind of util class as it appears quite a few times.

File: src/main/java/mcscheduler/model/ModelManager.java [hunk 2]
```diff
@@ -123,18 +122,21 @@ public void setWorker(Worker target, Worker editedWorker) {
         mcScheduler.setWorker(target, editedWorker);
     }
     @Override
-    public float calculateWorkerPay(Worker worker) {
+    public int calculateWorkerShiftsAssigned(Worker worker) {
         Integer numberOfShiftsAssigned = 0;
         ObservableList<Assignment> assignments = getFullAssignmentList();
         for (Assignment assignment : assignments) {
+            if (assignment.getRole() instanceof Leave) {
```
Comment (WangZijun97) [inline src/main/java/mcscheduler/model/ModelManager.java]: Perhaps will be better to use `Leave.isLeave`? Technically new Role("Leave") is also a leave but is not a `Leave` object (even though this is disallowed from happening by the factory method, just in case).
```suggestion
            if (Leave.isLeave(assignment.getRole())) {
```

**Review by WangZijun97 — APPROVED** [review]
Look good! Just a couple of small suggestions that I will leave up to you if you want to implement.

File: src/main/java/mcscheduler/model/ModelManager.java (hunk 2 above)
Comment (plosslaw) [reply src/main/java/mcscheduler/model/ModelManager.java]: Noted thanks for the suggestion

File: src/main/java/mcscheduler/logic/commands/CancelLeaveCommand.java (hunk 1 above)
Comment (plosslaw) [reply src/main/java/mcscheduler/logic/commands/CancelLeaveCommand.java:116]: The MESSAGE_USAGE is unique to each command and I don't want to pass in the Class object as a parameter into the function, let me know if you think we should abstract the function to CommandUtil and pass in the Class object or if there is another way without passing the Class object (Might have to change the string formatting).

Comment (plosslaw) [reply src/main/java/mcscheduler/logic/commands/CancelLeaveCommand.java:116]: Actually can remove the `%1$` in `Invalid command format\n%1$s` so we can just use normal string concatenation but might affect all functions using `MESSAGE_INVALID_COMMAND_FORMAT`

Comment (plosslaw) [reply src/main/java/mcscheduler/logic/commands/CancelLeaveCommand.java:116]: I changed the` printOutOfBoundsShiftIndexError` to take in an extra String parameter `messageUsage`, will be in next PR
